import { useState } from 'react'
import type { ScanResult } from '../types'
import { api } from '../api'

interface Props {
  lastScanResult: ScanResult | null
}

function downloadBlob(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type })
  const url  = URL.createObjectURL(blob)
  const a    = document.createElement('a')
  a.href     = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}

function passRateColor(rate: number) {
  if (rate >= 70) return 'var(--pass)'
  if (rate >= 50) return 'var(--warn)'
  return 'var(--fail)'
}

export default function ExportReport({ lastScanResult }: Props) {
  const [htmlLoading, setHtmlLoading] = useState(false)
  const [copied,      setCopied]      = useState(false)

  if (!lastScanResult) {
    return (
      <>
        <div className="page-header">
          <div className="page-title">Export report</div>
          <div className="page-sub">Download your compliance report</div>
        </div>
        <div className="card">
          <div className="empty-state">
            <div className="empty-state-icon"><DownloadEmptyIcon /></div>
            <div className="empty-state-title">No scan to export</div>
            <div className="empty-state-sub">Run a scan first, then come back to export.</div>
          </div>
        </div>
      </>
    )
  }

  const { id, timestamp, target, country, summary, scan_types } = lastScanResult
  const ts = new Date(timestamp).toLocaleString(undefined, {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit',
  })

  async function downloadHtml() {
    setHtmlLoading(true)
    try {
      const html = await api.htmlReport(lastScanResult!)
      downloadBlob(html, `kijiji-report-${country}-${id.slice(0, 8)}.html`, 'text/html')
    } catch {
      alert('Could not generate HTML report. Is the API server running?')
    } finally {
      setHtmlLoading(false)
    }
  }

  function downloadJson() {
    downloadBlob(
      JSON.stringify(lastScanResult, null, 2),
      `kijiji-report-${country}-${id.slice(0, 8)}.json`,
      'application/json',
    )
  }

  async function copySummary() {
    const text = [
      'Kijiji-Guard Compliance Report',
      `Date: ${ts}`,
      `Target: ${target}`,
      `Country: ${country}`,
      `Scanners: ${scan_types.join(', ')}`,
      `Pass rate: ${summary.pass_rate}%`,
      `Failed checks: ${summary.failed}`,
      `Total checks: ${summary.total}`,
      'Generated by Kijiji-Guard v0.1.0',
    ].join('\n')
    try {
      await navigator.clipboard.writeText(text)
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    } catch {
      alert('Copy failed — your browser may not support clipboard access.')
    }
  }

  return (
    <>
      <div className="page-header">
        <div className="page-title">Export report</div>
        <div className="page-sub">Download or share your compliance report</div>
      </div>

      {/* Preview card */}
      <div className="card" style={{ marginBottom: 20 }}>
        <div className="section-title" style={{ marginBottom: 14 }}>Scan summary</div>
        <div className="export-preview">
          <div className="preview-item">
            <div className="preview-label">Date</div>
            <div className="preview-value">{ts}</div>
          </div>
          <div className="preview-item">
            <div className="preview-label">Target</div>
            <div className="preview-value" style={{ fontFamily: 'monospace' }}>{target}</div>
          </div>
          <div className="preview-item">
            <div className="preview-label">Country</div>
            <div className="preview-value">{country}</div>
          </div>
          <div className="preview-item">
            <div className="preview-label">Scanners</div>
            <div className="preview-value">{scan_types.join(', ')}</div>
          </div>
          <div className="preview-item">
            <div className="preview-label">Pass rate</div>
            <div className="preview-value" style={{ color: passRateColor(summary.pass_rate), fontWeight: 600 }}>
              {summary.pass_rate}%
            </div>
          </div>
          <div className="preview-item">
            <div className="preview-label">Total / Passed / Failed</div>
            <div className="preview-value">
              {summary.total} &nbsp;/&nbsp;
              <span style={{ color: 'var(--pass)' }}>{summary.passed}</span>&nbsp;/&nbsp;
              <span style={{ color: 'var(--fail)' }}>{summary.failed}</span>
            </div>
          </div>
        </div>
      </div>

      {/* Export actions */}
      <div className="card">
        <div className="section-title" style={{ marginBottom: 16 }}>Export options</div>
        <div className="export-actions">
          <div className="export-btn-row">
            <button className="btn" onClick={downloadJson}>
              <DownloadIcon /> Download JSON report
            </button>
            <span className="export-btn-desc">Full scan result as structured JSON — ideal for CI/CD integration</span>
          </div>
          <div className="export-btn-row">
            <button className="btn btn-primary" onClick={downloadHtml} disabled={htmlLoading}>
              {htmlLoading
                ? <><span className="spinner" style={{ width: 13, height: 13 }} /> Generating…</>
                : <><DownloadIcon /> Download HTML report</>}
            </button>
            <span className="export-btn-desc">Standalone HTML file — what you show an auditor</span>
          </div>
          <div className="export-btn-row">
            <button className="btn" onClick={copySummary}>
              {copied ? <><CheckIcon /> Copied!</> : <><CopyIcon /> Copy summary</>}
            </button>
            <span className="export-btn-desc">Copy a text summary to clipboard</span>
          </div>
        </div>
      </div>
    </>
  )
}

function DownloadEmptyIcon() {
  return (
    <svg width="36" height="36" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  )
}
function DownloadIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="7 10 12 15 17 10" />
      <line x1="12" y1="15" x2="12" y2="3" />
    </svg>
  )
}
function CopyIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
      <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  )
}
function CheckIcon() {
  return (
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none"
      stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
      <polyline points="20 6 9 17 4 12" />
    </svg>
  )
}
